FROM alpine:3

LABEL author="Eka Putra Juniawan"
LABEL instansi="Universitas Udayana" github="https://github.com/ekaputra04"

RUN mkdir hello
RUN echo "Hello Eka Putra" > "hello/hello-eka.txt"

CMD cat "hello/hello-eka.txt"